"""
finalize_h5ad_task.py

Final stage of the downstream Azimuth WDL workflow. Merges reconciled
Azimuth labels into the per-batch Pegasus h5ad, attaches `individualID`
from a generic sample_to_individual mapping, re-runs HVG/PCA/Harmony/
Leiden/UMAP, and writes the final annotated h5ad.

Refactored from downstream/finalize_h5ad.py for use in the downstream
Terra WDL workflow (terra_wdl/downstream.wdl).

Changes from the original:
- All `elif study=="CMC"` / "UCLA-ASD" / "AMP-AD_ROSMAP" / "LIBD" /
  "PTSDBrainomics" / "SZBD-Kellis" branches removed. The hardcoded
  `/ysm-gpfs/...` and `/gpfs/...` paths and study-specific metadata
  joins were Slurm-era artifacts.
- Generic `--sample_to_individual_tsv` input replaces all study-specific
  individualID derivation logic.
- Single CLI flow; no `--hybrid` flag (the downstream WDL always operates
  on the Hybrid-filtered h5ad produced by Pegasus-Pipeline.py).
- Outputs written to current working directory for WDL capture.
"""

import argparse
import os

import numpy as np
import pandas as pd
import pegasus as pg
from pegasusio import MultimodalData
from scipy.spatial import distance


def load_sample_to_individual_map(tsv_path: str) -> dict:
    """
    Load a 2-column TSV mapping sample_tag -> individualID.
    Header row required: 'sample_tag', 'individualID'.
    Returns a dict {sample_tag: individualID}.
    """
    df = pd.read_csv(tsv_path, sep="\t")
    expected_cols = {"sample_tag", "individualID"}
    missing = expected_cols - set(df.columns)
    if missing:
        raise ValueError(
            f"sample_to_individual TSV must have columns {expected_cols}, "
            f"missing: {missing}. Found columns: {list(df.columns)}"
        )
    return dict(zip(df["sample_tag"], df["individualID"]))


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Merge reconciled Azimuth labels into the per-batch Pegasus "
            "h5ad and produce the final annotated h5ad with individualID "
            "metadata and re-clustered UMAP."
        )
    )
    parser.add_argument(
        "--h5ad", required=True,
        help="Path to the Pegasus Hybrid_filtered h5ad."
    )
    parser.add_argument(
        "--azimuth_csv", required=True,
        help=(
            "Path to the reconciled Azimuth predictions CSV from "
            "reconcile_labels.py."
        )
    )
    parser.add_argument(
        "--sample_to_individual_tsv", required=True,
        help=(
            "Path to the 2-column TSV mapping sample_tag to individualID. "
            "Generated by generate_sample_table.py --write_individual_map."
        )
    )
    parser.add_argument(
        "--batch_name", required=True,
        help="Batch name used in the output filename."
    )
    parser.add_argument(
        "--resolution", type=float, default=4.5,
        help=(
            "Leiden re-clustering resolution after Azimuth label merge "
            "(default: 4.5). Use 4.0 for SZBD-Kellis-like data."
        )
    )
    parser.add_argument(
        "--n_jobs", type=int, default=8,
        help="Number of CPU cores for parallel ops (default: 8)."
    )
    args = parser.parse_args()

    # ------------------------------------------------------------------
    # 1. Load Pegasus h5ad
    # ------------------------------------------------------------------
    print(f"[1/6] Loading Pegasus h5ad: {args.h5ad}")
    data = pg.read_input(args.h5ad)

    # Sanity check: raw and log-normalized matrices should be consistent
    data.select_matrix("raw.X")
    mat_raw = data.X.todense()
    data.select_matrix("X")
    mat_norm = data.X.todense()

    test = np.zeros(mat_raw.shape[0])
    for i in range(mat_raw.shape[0]):
        test[i] = 1 - distance.cosine(
            np.array(mat_raw[i])[0], 2 ** (np.array(mat_norm[i])[0])
        )
    print(f"  Raw vs norm cosine correlation: "
          f"min={np.min(test):.4f}, max={np.max(test):.4f}")

    # ------------------------------------------------------------------
    # 2. Merge reconciled Azimuth labels into obs
    # ------------------------------------------------------------------
    print(f"[2/6] Merging Azimuth labels from {args.azimuth_csv}")
    az_df = pd.read_csv(args.azimuth_csv, header=0)
    az_df.columns = ["barcodekey", "azimuth"]
    az_df = az_df.set_index("barcodekey")
    print(f"  Azimuth predictions: {len(az_df)} cells")

    data.obs = pd.concat([data.obs, az_df], axis=1)

    # Drop cells without an Azimuth call. Only check the freshly-merged
    # 'azimuth' column; checking the whole obs frame would drop cells that
    # have NaNs in unrelated upstream QC columns.
    keep_mask = data.obs["azimuth"].notnull().to_numpy()
    n_before = data.obs.shape[0]
    data = MultimodalData(data[keep_mask].copy())
    print(f"  After dropping cells without Azimuth: "
          f"{data.obs.shape[0]} cells (dropped {n_before - data.obs.shape[0]})")

    # Extract subclass (label component before any '-' suffix)
    data.obs["subclass"] = data.obs["azimuth"].astype(str).str.split("-").str[0]

    # ------------------------------------------------------------------
    # 3. Attach individualID via generic sample_to_individual map
    # ------------------------------------------------------------------
    print(f"[3/6] Attaching individualID from {args.sample_to_individual_tsv}")
    sample_to_ind = load_sample_to_individual_map(args.sample_to_individual_tsv)
    print(f"  Loaded {len(sample_to_ind)} sample -> individual mappings")

    # Pegasus uses 'Channel' as the per-sample column; it should match the
    # sample_tag used in the WDL inputs.
    if "Channel" not in data.obs.columns:
        raise ValueError(
            "Expected 'Channel' column in h5ad obs (set by Pegasus during "
            "aggregate_matrices). Cannot attach individualID."
        )

    channels = sorted(set(data.obs["Channel"].astype(str).tolist()))
    print(f"  Channels in h5ad: {channels}")

    def lookup_individual(channel_value: str) -> str:
        # Try exact match first
        if channel_value in sample_to_ind:
            return sample_to_ind[channel_value]
        # Fallback: strip common per-HTO suffixes (e.g., '-HTO1')
        base = channel_value.split("-")[0]
        if base in sample_to_ind:
            return sample_to_ind[base]
        # Unknown: keep as the channel value so cells aren't silently lost
        print(f"  WARNING: no individualID mapping for Channel '{channel_value}'")
        return channel_value

    data.obs["sampleID"] = data.obs["Channel"]
    data.obs["individualID"] = data.obs["Channel"].astype(str).map(
        lookup_individual
    )

    # ------------------------------------------------------------------
    # 4. Re-cluster (HVG -> PCA -> Harmony -> kNN -> Leiden -> UMAP)
    # ------------------------------------------------------------------
    print(f"[4/6] Re-clustering at Leiden resolution {args.resolution}")
    pg.highly_variable_features(data, batch="Channel", n_top=5000)
    pg.pca(data, n_jobs=args.n_jobs)
    pca_key = pg.run_harmony(data, n_jobs=args.n_jobs)
    pg.neighbors(data, rep=pca_key, n_jobs=args.n_jobs, use_cache=False)
    pg.cluster(data, algo="leiden", rep=pca_key, resolution=args.resolution)
    pg.umap(data, rep=pca_key, n_jobs=args.n_jobs)

    # ------------------------------------------------------------------
    # 5. Clean up transient obs/var columns
    # ------------------------------------------------------------------
    print("[5/6] Cleaning up transient columns")
    drop_obs = [c for c in ["doublet", "doublet_score", "scale", "leiden_labels"]
                if c in data.obs.columns]
    if drop_obs:
        data.obs = data.obs.drop(drop_obs, axis=1)
    drop_var = [c for c in
                ["robust", "highly_variable_features", "mean", "var",
                 "hvf_loess", "hvf_rank"]
                if c in data.var.columns]
    if drop_var:
        data.var = data.var.drop(drop_var, axis=1)

    # ------------------------------------------------------------------
    # 6. Write final h5ad
    # ------------------------------------------------------------------
    outfile = f"./{args.batch_name}_annotated.h5ad"
    print(f"[6/6] Writing final annotated h5ad: {outfile}")
    pg.write_output(data, outfile)
    print("Done.")


if __name__ == "__main__":
    main()
